name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      checks: write

    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go build ./...

      - run: go test ./...

      - name: Set up Docker Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This is the builder role, created by terraform. `terraform/envs/eng/build` `builder_role`
          role-to-assume: arn:aws:iam::905418421134:role/github-actions
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # We don't use the build-push action, because our tests run using temporary containers, and we need to pass in the docker socket.
      - name: Build and push
        run: |
          docker build --push -t 905418421134.dkr.ecr.us-east-1.amazonaws.com/grpcmcp:${{ github.sha }} .
